### ISSUE TITLE
User Configurable Text Labels

### ISSUE THREAD

**Issue by kvanderhoek** [johrstrom/jmeter-prometheus-plugin#37] opened 2019-01-23 22:02 UTC
The InfluxDB listener has fields such as 'measurement', 'application', and 'testTitle' that can be configured in the Listener UI in JMeter.  Having one or two user configurable text fields can be really handy as it allows automation to pass in metadata about the test to JMeter which Jmeter can then pass on to the metrics reporting solution. For instance, variables such as Environment, Test Type, Test Name can be passed as a Label to Prometheus, Grafana, etc where you can filter on them.  This allows you to do queries such as "Show me test results run on CI environment" or "Show me test results for testTitle Nightly-Test".  It would be great to see a couple of user configurable text labels implemented in this Prometheus listener.

<img width="994" alt="screen shot 2019-01-23 at 1 58 36 pm" src="https://user-images.githubusercontent.com/4307769/51640031-4ee74900-1f17-11e9-99b7-b8a06c2c7d65.png">

**Comment by johrstrom** [comment] 2019-01-23 22:24
Again, thanks for the other example and the ticket in general.   I'm closing this issue as a duplicate of https://github.com/johrstrom/jmeter-prometheus-plugin/issues/36. Please see my comments there and we can continue the discussion/progress there.

**Closed by johrstrom** 2019-01-23 22:24 UTC
